version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pruthviraj-backend-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/pruthviraj_db
      - REDIS_URL=redis://redis:6379
      - JWT_ACCESS_SECRET=pruthviraj_access_secret_super_secure_key_2026
      - JWT_REFRESH_SECRET=pruthviraj_refresh_secret_super_secure_key_2026
      - UPLOAD_DIR=/app/uploads
      - APP_URL=http://localhost:5000
      - CORS_ORIGINS=*
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pruthviraj-network

  mongodb:
    image: mongo:7.0
    container_name: pruthviraj-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pruthviraj-network

  redis:
    image: redis:7.2-alpine
    container_name: pruthviraj-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pruthviraj-network

volumes:
  mongo_data:
  redis_data:

networks:
  pruthviraj-network:
    driver: bridge
